---
- hosts: web1
  become: yes
  gather_facts: yes
  tasks:
  - name: Allow https from controller
    firewalld: source=172.20.1.2 service=https state=enabled zone=internal immediate=true permanent=true