---
- hosts: all
  gather_facts: no
  become: yes
  tasks:
    - name: Make changes in Apache config
      replace:
        path: /etc/httpd/conf/httpd.conf
        regexp: "^Listen 80"
        replace: "Listen 443"
    - name: Restart HTTPD service
      service: name=httpd state=restarted