---
- hosts: web1
  become: yes
  tasks:
  - name: 'Add content to file'
    blockinfile:
      path: /var/www/html/index.html
      insertbefore: BOF
      create: true
      owner: apache
      group: apache
      block: |
        'Welcome to KodeKloud!
        This is Ansible Lab.'