---
  - hosts: web1
    become: yes
    tasks:
    - name: Install sudo package
      package: name=sudo state=present
    - name: Install vsftpd package
      package: name=vsftpd-2.2.2 state=installed allow_downgrade=yes