---
- hosts: web1
  become: yes
  gather_facts: yes
  tasks:
  - name: Install Nginx package
    package: name=nginx state=present
  - name: Start Nginx service
    service: name=nginx state=started enabled=yes